apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
  labels:
    app: ecommerce
    component: config
data:
  # Database Configuration
  MONGODB_URI: "mongodb://admin:password@mongodb-service:27017/amazona?authSource=admin"
  
  # Application Configuration
  PORT: "5000"
  NODE_ENV: "production"
  JWT_SECRET: "somethingsecret"
  PAYPAL_CLIENT_ID: "sb"
  
  # AWS Configuration (Update these for your AWS setup)
  AWS_REGION: "us-east-1"  # Updated to match your EKS region
  AWS_BUCKET_NAME: "amazona20"
  
  # Frontend Configuration
  REACT_APP_API_URL: "http://api.amazona.local"  # Will be updated based on ingress
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
  labels:
    app: ecommerce
    component: secrets
type: Opaque
data:
  # AWS Credentials (Base64 encoded)
  AWS_ACCESS_KEY_ID: "QUtJQVNVU0pFREhNRU9VRlhLWDU="
  AWS_SECRET_ACCESS_KEY: "NXlmMy9hMXhiK2x2SHREQ0lzb2doblR0QjdydVc2eGJpUWlKYnBUdQ=="
  
  # MongoDB Credentials (Base64 encoded: admin / password)
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="
