apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  MONGODB_URI: "mongodb://admin:password@mongodb-service:27017/amazona?authSource=admin"
  PORT: "5000"
  NODE_ENV: "production"
  REACT_APP_API_URL: "https://amazona.com"
  JWT_SECRET: "somethingsecret"
  PAYPAL_CLIENT_ID: "sb"
  AWS_REGION: "eu-north-1"
  AWS_BUCKET_NAME: "amazona20"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QUtJQVNVU0pFREhNRU9VRlhLWDU="
  AWS_SECRET_ACCESS_KEY: "NXlmMy9hMXhiK2x2SHREQ0lzb2doblR0QjdydVc2eGJpUWlKYnBUdQ=="
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="