apiVersion: batch/v1
kind: Job
metadata:
  name: seed-products-job
  namespace: ecommerce
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: seed-products
        image: elshahat20/my-app:itiBack-1.0.2
        command: ["npm", "run", "seed-prod"]
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: MONGODB_URI
        - name: NODE_ENV
          value: "production"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: AWS_REGION
        - name: AWS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: AWS_BUCKET_NAME
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: JWT_SECRET
      backoffLimit: 3
